// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID          uuid.UUID
	Title       string
	Priority    int16
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt sql.NullTime
	DeletedAt   sql.NullTime
}
