// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, title)
VALUES ($1, $2)
RETURNING id, title, created_at, updated_at, completed_at, deleted_at
`

type CreateTaskParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.ID, arg.Title)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteTask = `-- name: HardDeleteTask :execrows
DELETE FROM tasks
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteTask(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, hardDeleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listCompletedTasks = `-- name: ListCompletedTasks :many
SELECT id, title, created_at, updated_at, completed_at, deleted_at
FROM tasks
WHERE completed_at IS NOT NULL AND deleted_at IS NULL
ORDER BY
    CASE WHEN $1 = 'asc' THEN completed_at END ASC,
    CASE WHEN $1 = 'desc' THEN completed_at END DESC
`

func (q *Queries) ListCompletedTasks(ctx context.Context, sortOrder interface{}) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedTasks, sortOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedTasks = `-- name: ListDeletedTasks :many
SELECT id, title, created_at, updated_at, completed_at, deleted_at
FROM tasks
WHERE deleted_at IS NOT NULL
ORDER BY
    CASE WHEN $1 = 'asc' THEN deleted_at END ASC,
    CASE WHEN $1 = 'desc' THEN deleted_at END DESC
`

func (q *Queries) ListDeletedTasks(ctx context.Context, sortOrder interface{}) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedTasks, sortOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT id, title, created_at, updated_at, completed_at, deleted_at
FROM tasks
WHERE completed_at IS NULL AND deleted_at IS NULL
ORDER BY
    CASE WHEN $1 = 'asc' THEN created_at END ASC,
    CASE WHEN $1 = 'desc' THEN created_at END DESC
`

func (q *Queries) ListPendingTasks(ctx context.Context, sortOrder interface{}) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTasks, sortOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, created_at, updated_at, completed_at, deleted_at
FROM tasks
WHERE deleted_at IS NULL
ORDER BY
    CASE WHEN $1 = 'asc' THEN created_at END ASC,
    CASE WHEN $1 = 'desc' THEN created_at END DESC
`

func (q *Queries) ListTasks(ctx context.Context, sortOrder interface{}) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, sortOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskDone = `-- name: MarkTaskDone :exec
UPDATE tasks
SET completed_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) MarkTaskDone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markTaskDone, id)
	return err
}

const markTaskUndone = `-- name: MarkTaskUndone :exec
UPDATE tasks
SET completed_at = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) MarkTaskUndone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markTaskUndone, id)
	return err
}

const restoreDeletedTask = `-- name: RestoreDeletedTask :exec
UPDATE tasks
SET deleted_at = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreDeletedTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restoreDeletedTask, id)
	return err
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteTask, id)
	return err
}
